### ISSUE TITLE
Binaries for other platforms

### ISSUE THREAD

**Issue by pedrocamargo** [coleifer/pysqlite3#13]
The Github runners for the workflows have dumbed down SQLite3 versions.  It would be nice to be able to install these binaries in all platforms (it works perfectly on Linux)

**Comment by coleifer** [comment]
Huh?

Have you tried `pysqlite3-binary` package?

**Comment by pedrocamargo** [comment]
I have, and PyPi accuses that only binaries for Linux are available

https://pypi.org/project/pysqlite3-binary/#files

**Comment by coleifer** [comment]
I have no idea what a github runner is, or what it has to do with this, can you clarify?

**Comment by pedrocamargo** [comment]
The Github runners are the virtual machines used to run automated testing (Github actions). The SQLite3 dll shipped with the Python distributions available in these VMs are really dumbed down, so one can't test any software using some of the capabilities from SQLite (e.g. RTree).
That is also true for Vanilla Python distributions for Windows, for example, and having binaries to Pip install would solve those issues.

**Comment by pedrocamargo** [comment]
If I work in automated building procedures for pysqlite3, would you be interested in me issuing a pull request?

**Comment by mihow** [comment]
@pedrocamargo +1 for automated build procedures! Thank you for offering to issue a pull request. Does your offer still stand? Automated builds for other platforms seems very important for the stability of this project.

**Comment by pedrocamargo** [comment]
There is no longer a need for this, as explored in the linked thread above.  There are already wheels being produced for all operating systems.
