### ISSUE TITLE
Where is zeroblob ?

### ISSUE THREAD

**Issue by bozhinov** [coleifer/pysqlite3#16]
Hello,

I m unable to find the zeroblob implementation

In the commit for bpo-24905 it is used with no namespace

Thanks
Momchil

**Comment by coleifer** [comment]
I think you are mistaken. `zeroblob()` is a sqlite function and is not exposed in pysqlite3 or in the changes for bpo-24905 https://github.com/python/cpython/pull/271

**Comment by bozhinov** [comment]
If it is not exported how do I use it ?
I see it [here:](https://github.com/coleifer/pysqlite3/blob/182333af05aafa6f5add7af2c8d1cb46dbd42363/test/dbapi.py#L954)

**Comment by coleifer** [comment]
That is a functional being executed within a SQL query, and corresponds to a sqlite built-in:

https://sqlite.org/lang_corefunc.html#zeroblob

**Comment by bozhinov** [comment]
Apologies. I get it now.
Thank you.

**Comment by bozhinov** [comment]
ahh .. I can't use it like this. 
allocates like 200Mb of memory and I m only trying to zeroblob a byte array of 10
Chances are this is a sqlite problem and not python right ?
