### ISSUE TITLE
Uninstall not possible with pip

### ISSUE THREAD

**Issue by bozhinov** [coleifer/pysqlite3#17]
C:\Python38>Scripts\pip install pysqlite3
Collecting pysqlite3
  Using cached pysqlite3-0.4.3.tar.gz (40 kB)
Using legacy 'setup.py install' for pysqlite3, since package 'wheel' is not installed.
Installing collected packages: pysqlite3
    Running setup.py install for pysqlite3 ... done
Successfully installed pysqlite3

C:\Python38>Scripts\pip uninstall pysqlite3
WARNING: Skipping pysqlite3 as it is not installed.

Does not show under pip list either

pip version 20.2.4
python version 3.8.6 x64

**Comment by coleifer** [comment]
Not sure what this might be related to, but I don't plan to pursue this.
