### ISSUE TITLE
Feature suggestion: expose sqlite3_column_database_name family of functions

### ISSUE THREAD

**Issue by simonw** [coleifer/pysqlite3#18]
Bit of a niche feature request this one: I'm really interested in these APIs: https://www.sqlite.org/c3ref/column_database_name.html
```
const char *sqlite3_column_database_name(sqlite3_stmt*,int);
const char *sqlite3_column_table_name(sqlite3_stmt*,int);
const char *sqlite3_column_origin_name(sqlite3_stmt*,int);
```
Given a prepared statement they let you figure out which database/table/column the return values come from. [For example](https://latest.datasette.io/fixtures?sql=select%0D%0A++roadside_attractions.name+as+name%2C%0D%0A++attraction_characteristic.name%0D%0Afrom%0D%0A++roadside_attraction_characteristics%0D%0A++join+roadside_attractions+on+roadside_attraction_characteristics.attraction_id+%3D+roadside_attractions.pk%0D%0A++join+attraction_characteristic+on+roadside_attraction_characteristics.characteristic_id+%3D+attraction_characteristic.pk%0D%0A):
```sql
select
  roadside_attractions.name as name,
  attraction_characteristic.name as characteristic
from
  roadside_attraction_characteristics
  join roadside_attractions on roadside_attraction_characteristics.attraction_id = roadside_attractions.pk
  join attraction_characteristic on roadside_attraction_characteristics.characteristic_id = attraction_characteristic.pk
```
The `sqlite3_column_database_name` family of APIs could let me examine this SQL query and identify that the `name` column in the output came from the `roadside_attractions.name` column, but the `characteristic` column was from `attraction_characteristic.name`.

I have a couple of use-cases for this:

- If a query returns a 5MB binary object in a BLOB column I'd like to display "5MB binary" and provide a download link, where the download link knows how to query just that data. Knowing which dataase/table/column it came from would help.
- In Datasette I like displaying foreign key references as hyperlinks, as seen on https://latest.datasette.io/fixtures/roadside_attraction_characteristics - if I could tell the table/columns responsible for a value on my arbitrary SQL query page ([this page](https://latest.datasette.io/fixtures?sql=select+rowid%2C+attraction_id%2C+characteristic_id+from+roadside_attraction_characteristics+order+by+rowid+limit+101)) I could show the hyperlinks there as well.

**Comment by simonw** [comment]
I've not yet managed to come up with a proposed design for a Python API that exposes this stuff. Maybe something on the cursor after `cursor.execute(sql)` has been called?

**Comment by coleifer** [comment]
These require that the underlying library be compiled with `SQLITE_ENABLE_COLUMN_METADATA`, which must be specifically enabled by the user. For what it's worth, apsw does not support this family of functions. Most of the information can already be obtained from the cursor description, but beyond that I agree with Roger that this seems to provide very little real-world utility. I'd suggest tackling this at the application layer instead.

If upstream does end up adding this functionality I will definitely merge it in, but at the moment I'll probably pass.
