### ISSUE TITLE
Does'nt build pysqlite3

### ISSUE THREAD

**Issue by DiKey98** [coleifer/pysqlite3#19]
![image](https://user-images.githubusercontent.com/34924546/97197418-b0101080-17be-11eb-9ef3-8d998c64044f.png)

**Comment by DiKey98** [comment]
I had installed libsqlite3-dev and python-sqlite, but errors remained

**Comment by coleifer** [comment]
Yeah, as the README says:

>This library takes the SQLite module from Python 3 and packages it as a separately-installable module.

You're using python 2.7.
