### ISSUE TITLE
Have this generate binary wheels with latest amalgamation and ship them to PyPI

### ISSUE THREAD

**Issue by simonw** [coleifer/pysqlite3#2]
I'm really interested in this project at the moment.

SQLite 3.25.0 is due to ship shortly and will add support for [window functions](
https://www.sqlite.org/draft/windowfunctions.html), which is really exciting - but the actual version of SQLite that is available in the standard library sqlite3 module is tied to the underlying operating system and is often very out of date (the Travis CI default build environment still exposes SQLite 3.8 for example!)

I would love to see this project published to PyPI with the latest stable version of the SQLite amalgamation compiled into it, in a binary wheel format such that it can be "pip install"ed on as many platforms as posssible.

I haven't worked with binary compiled wheels myself, but I would be happy to dig in and help figure out how best to do this. 
https://github.com/biopython/biopython/issues/1296 has some useful notes and 
https://github.com/pypa/manylinux looks relevant. I've done a fair amount of work with Travis CI recently and it can provide build environments for both Linux and OS X (I have no idea how windows would work).

**Comment by simonw** [comment]
I see you are already [totally on top of the new window functions stuff](
https://github.com/coleifer/pysqlite3/commit/530294c38c134abd627e2847229236bc510ac841)!

**Comment by coleifer** [comment]
Yes, I posted it to HN a while back but it didn't receive much traction -- glad to see it on the front page today.

I've gotten pretty good at working with travis -- the peewee build has gotten pretty nice (including running against the latest sqlite for one round of tests). Unfortunately, I'm not at all sure how to manage "wheels". Do you need to build separate wheels for x64, x86, arm, darwin, windows? Does it make sense to have users of this library default to running a particular version of sqlite with such-and-such features compiled by default?

Honestly, it's very little work to compile your own sqlite with exactly the features you want, and it's just a tiny bit more effort to create a pysqlite3 that is statically-linked. Info here: http://charlesleifer.com/blog/compiling-sqlite-for-use-with-python-applications/

**Comment by simonw** [comment]
It looks like you need to produce a few different wheels for different platforms. The best example I've found so far is this biopython repo which handles all of their wheel generation https://github.com/biopython/biopython-wheels

You can see their results on PyPI - https://pypi.org/project/biopython/

Selfishly, my principle goal is that I'd like to be able to run `pip install pysqlite3` (or maybe `pip install pysqlite3==3.25.0` or some other package name if you don't want the default package to include the amalgamation) on the platforms I care about (OS X and Linux) and get a working module. Then I can give tutorials on how to use the latest SQLite3 features without having to coach people through a build and compilation step first.

**Comment by simonw** [comment]
http://charlesleifer.com/blog/compiling-sqlite-for-use-with-python-applications/ is fantastic, I hadn't seen that - it's exactly the documentation I was needing. Thanks!

**Comment by simonw** [comment]
The documentation for https://github.com/matthew-brett/multibuild looks pretty comprehensive. It includes scripts for building wheels on Travis CI (for OS X and Linux) and AppVeyor (for Windows).

**Comment by simonw** [comment]
I just successfully installed pysqlite3 with 3.25.0 into a fresh virtual environment using the fork at https://github.com/karlb/pysqlite3

```
$ python3 -mvirtualenv venv
$ source venv/bin/activate
$ pip install git+git://github.com/karlb/pysqlite3
Collecting git+git://github.com/karlb/pysqlite3
...
Installing collected packages: pysqlite3
Successfully installed pysqlite3-0.2.0
$ python
Python 3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysqlite3
>>> pysqlite3.connect(":memory:").execute("select sqlite_version()").fetchall()
[('3.25.0',)]
```

**Comment by simonw** [comment]
Here's a deployed Datasette instance using pysqlite3: https://pysqlite3-datasette.now.sh/fivethirtyeight-2628db9?sql=select+sqlite_version%28%29

**Comment by stonebig** [comment]
lastest sqlite-3.28.0 contains even more window function stuff.

````
In SQLite version 3.28.0 (2019-04-16), windows function support was extended to include:
- the EXCLUDE clause,
- GROUPS frame types,
- window chaining, 
- and support for "<expr> PRECEDING" and "<expr> FOLLOWING" boundaries in RANGE frames.
````

**Comment by coleifer** [comment]
Yep, those are all supported in the latest releases of peewee, by the way:

https://github.com/coleifer/Peewee

**Comment by JakaKokosar** [comment]
> Honestly, it's very little work to compile your own sqlite with exactly the features you want, and it's just a tiny bit more effort to create a pysqlite3 that is statically-linked. Info here: http://charlesleifer.com/blog/compiling-sqlite-for-use-with-python-applications/

How does this help me if I want to distribute some project with pysqlite3 (to ensure I have SQLite extensions project depends on) as a dependency? Installation of pysqlite3 will always produce this [RuntimeError](https://github.com/coleifer/pysqlite3/blob/master/setup.py#L67) since amalgamation files are missing by default.

 Sadly I'm no expert when it comes to python packaging and I can't see an obvious solution other than having wheels on the PyPI.

Arguably building wheels now days is not that big of a problem. I have a working example here https://github.com/JakaKokosar/pysqlite3. This produces wheels using [Azure Pipelines on all major platform. ](https://dev.azure.com/jakakokosar/pysqlite3/_build/results?buildId=227)

<img width="828" alt="Screenshot 2019-08-27 at 19 01 58" src="https://user-images.githubusercontent.com/15876321/63792126-31d78600-c8fd-11e9-95b6-82d902361510.png">

**Comment by simonw** [comment]
@JakaKokosar this is brilliant!

I've been meaning to spend some time figuring out how to do this (especially the manylinux bit and the different wheels for different platforms) for nearly a year now.

Suggestion: publish what you've got to PyPI under a different package name from `pysqlite3` - I suggest `pysqlite3-binary` because that matches the pattern established by https://pypi.org/project/psycopg2-binary/

**Comment by coleifer** [comment]
@JakaKokosar - fine work, I'm happy for people to use pysqlite3-binary if they find it useful. Building wheels looks very complicated. I have avoided vendoring sqlite3's source code for all the obvious reasons. An alternative would be to provide a separate command to fetch the source amalgamation, a-la [apsw](https://github.com/rogerbinns/apsw/blob/cab2aeab9e061a1151ee0858330cca81444ab0cc/setup.py#L207-L487). Again, something I've avoided. Thanks for sharing this.

**Comment by coleifer** [comment]
So after being overwhelmed by trying to make sense of what those pipelines are doing, I think I've got a better idea of how this all works. I've put together two shell scripts -- the first grabs the code and runs the pypa manylinux docker image, invoking the second script within the container, which builds the actual wheels and makes them available as usable build artifacts.

So it should be straightforward to put those wheels in the `dist/` directory and send them off to pypi, I think (?). Looks like pip prefers wheels when possible and to get a straight-up source install you need to pass `--no-binary :all:` to get the current behavior.

For this reason, I don't really want to make wheels the default, as it pretty much restricts you to using whatever amalgamation I pick, along with the compile-time options specified in the `setup.py`.

Additionally, it seems tricky to get macos and windows wheels built without resorting to something like azure pipelines. I think travis-ci supports mac but not windows(?), but I'm leery of having travis-ci upload packages to pypi anyways.

This has been both more and less painful than I thought it would be.

**Comment by coleifer** [comment]
I was curious how `psycopg2` managed the whole different names thing and they're just using `sed` to hack the project name at wheel-building time, so that seemed acceptable to me.

Here's what I scraped together:

```sh
#!/bin/bash

set -e -x

# TODO: obtain latest stable release?
sqlite_src="$HOME/code/sqlite"
if [[ ! -d "$sqlite_src" ]]; then
  echo "Sqlite source code not found."
  exit 1
fi

if [[ ! -d "./pysqlite3" ]]; then
  git clone git@github.com:coleifer/pysqlite3
  sed -i "s|name=PACKAGE_NAME|name='pysqlite3-binary'|g" pysqlite3/setup.py
fi

cp "${sqlite_src}/sqlite3.c" pysqlite3/
cp "${sqlite_src}/sqlite3.h" pysqlite3/

docker run -it -v $(pwd):/io quay.io/pypa/manylinux1_x86_64 /io/build_wheels.sh
```

The following script is run inside the docker container:

```sh
#!/bin/bash

# Volume (cwd of build script) is mounted at /io.
# A checkout of pysqlite3 is cloned beforehand by the build.sh script.
cd /io/pysqlite3

PY36="/opt/python/cp36-cp36m/bin"
"${PY36}/python" setup.py build_static
"${PY36}/pip" wheel /io/pysqlite3 -w /io/wheelhouse

PY37="/opt/python/cp37-cp37m/bin"
"${PY37}/python" setup.py build_static
"${PY37}/pip" wheel /io/pysqlite3 -w /io/wheelhouse

for whl in /io/wheelhouse/*.whl; do
  auditwheel repair "$whl" -w /io/wheelhouse/
done
```

Then in the directory of the build scripts I have a `wheelhouse/` directory with the manylinux wheels all ready to go and named "pysqlite3-binary". I'd like to refine this a bit, but am satisfied with this after a couple hours work.

**Comment by coleifer** [comment]
Ugh, looking at the wheels I built, it appears that the pure python is installed into `pysqlite3` while the c extension is installed into `pysqlite3-binary`... Any ideas on what I might have missed would be appreciated, otherwise I'll mess with it tomorrow.

**Comment by coleifer** [comment]
Got it sorted out. Have to swap the package name *after* building the extension but *before* making the wheel.
