### ISSUE TITLE
Binary wheel for python3.9

### ISSUE THREAD

**Issue by AustEcon** [coleifer/pysqlite3#20]
Hi. Can you please kindly add python 3.9 support for the pypi linux wheel?

**Comment by coleifer** [comment]
I've added this, thanks for requesting. I think I had tried this before, but I hadn't updated my manylinux image. Anyways, 0.4.5 of pysqlite3-binary should support 3.9 now.

**Comment by AustEcon** [comment]
Legend! Thanks 😉
