### ISSUE TITLE
Can not import pysqlite3 when site-package is an egg

### ISSUE THREAD

**Issue by sleblanc** [coleifer/pysqlite3#21]
I built the latest pysqlite3 from source with the latest sqlite3 version. build and deploy went as expected. When testing - I got the following error:

Python 3.9.1 (default, Jan 14 2021, 00:41:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssn/dev/pysqlite3-0.4.5/pysqlite3/__init__.py", line 23, in <module>
    from pysqlite3.dbapi2 import *
  File "/home/ssn/dev/pysqlite3-0.4.5/pysqlite3/dbapi2.py", line 28, in <module>
    from pysqlite3._sqlite3 import *
ModuleNotFoundError: No module named 'pysqlite3._sqlite3'
>>> .quit
  File "<stdin>", line 1
    .quit
    ^
SyntaxError: invalid syntax
>>> quit()

Note that the python build is in alternate location.  When I unzipped the egg in the same site-packages location - all worked as expected.

Python 3.9.1 (default, Jan 14 2021, 00:41:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysqlite3
>>> pysqlite3.sqlite_version
'3.34.0'
>>> pysqlite3.version
'2.6.0'
>>> from pysqlite3 import dbapi2 as sqlite3
>>> sqlite3.version
'2.6.0'
>>> sqlite3.sqlite_version
'3.34.0'
>>> quit()

Any ideas??

**Comment by coleifer** [comment]
It seems you didn't compile it, or the compiled version is located somewhere else (likely in a ``build/`` subdirectory?). It depends on how you compiled it, how you have your pythonpath configured, etc., which are not really pysqlite3 issues.
