### ISSUE TITLE
Importing pysqlite3

### ISSUE THREAD

**Issue by pashshoev** [coleifer/pysqlite3#23]
Hi, on Windows 10  
When I have installed as "python setup.py build: 

I can't import pysqilte3 after installing, there is an error 
"ModuleNotFoundError                       
 in --> from pysqlite3._sqlite3 import *  
....      
ModuleNotFoundError: No module named 'pysqlite3._sqlite3"
there is no file _.sqlite3 

When I'm trying to install as "pip install pysqlite3-binary"
ERROR: Could not find a version that satisfies the requirement pysqlite3-binary (from versions: none)
ERROR: No matching distribution found for pysqlite3-binary

Could you help me please?

**Comment by pashshoev** [comment]
![Снимок экрана (306)](https://user-images.githubusercontent.com/80707446/114269680-0ee5e100-9a11-11eb-8115-7643d4ee949b.png)
![Снимок экрана (307)](https://user-images.githubusercontent.com/80707446/114269683-10170e00-9a11-11eb-9706-5e6b115c5a70.png)

**Comment by coleifer** [comment]
I do not produce windows builds of pysqlite3-binary, and to compile it you will need `sqlite3.h` installed.
