### ISSUE TITLE
Include `iterdump` utility from stdlib sqlite3

### ISSUE THREAD

**Issue by evansd** [coleifer/pysqlite3#24]
I've hit one case where pysqlite3 isn't quite a drop-in replacement for sqlite3 and that's the [Connection.iterdump](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.iterdump) method, which pysqlite3 doesn't support.

It's implemented as a Python function in [Lib/sqlite3/dump.py](https://github.com/python/cpython/blob/77d668b1221d0f8c3e9d6b6199f67aaf3c45f040/Lib/sqlite3/dump.py) which is then hooked into in [Modules/_sqlite/connection.c](https://github.com/python/cpython/blob/77d668b1221d0f8c3e9d6b6199f67aaf3c45f040/Modules/_sqlite/connection.c#L1531-L1581).

This isn't much of a problem as it's possible to import `sqlite3.dump._iterdump` directly and just pass the connection object to it (as we've done [here](https://github.com/ebmdatalab/openprescribing/commit/ba51c5599c1afd507461bb220dbad10e06a16eed)) but it would be nice if pysqlite3 gave us a strict superset of the sqlite3 API.

More generally, are there any docs on how the stdlib sqlite3 Python code needs to be modified for use in pysqlite3? Is it literally just replacing `from _sqlite3 import *` with `from pysqlite3._sqlite3 import *` or is it more involved? I can see the C code in `src` has recent upstream changes merged in but it looks like the Python code in `pysqlite3` hasn't been updated in a couple of years. I'd be happy to look at a PR for this if I knew where to start.

**Comment by coleifer** [comment]
That method is a gross hack, in my opinion, which is the reason I've excluded it from pysqlite3.

I've provided hooks into sqlite3's built-in [backup api](https://www.sqlite.org/backup.html) which should be considered a more correct, robust, and performant alternative.

>More generally, are there any docs on how the stdlib sqlite3 Python code needs to be modified for use in pysqlite3?

No documentation per-se, but the standard db-api 2.0 stuff is all compatible. Most of the non-standard sqlite3 stuff is also compatible (with the exception of iterdump, as you noted).

**Comment by evansd** [comment]
It is indeed a gross hack! And I totally get why you'd exclude it. The only reason we were using it was as a super lazy way to assert, in a test case, that an in-memory database and on on disk database had exactly the same contents. I wouldn't want to use it as a proper backup API.

The only reason I mentioned it was that it was a slight violation of my mental model of pysqlite3 as being stdlib sqlite3, plus extra features. But that's fine; I just need to update my mental model a tiny bit.

Thanks!

**Comment by simonw** [comment]
I have a use-case which isn't covered by the `.backup()` method: my `sqlite-utils` tool includes a feature for dumping out the current database to standard output:
```
% sqlite-utils dump /tmp/strict-table.db 
BEGIN TRANSACTION;
CREATE TABLE foo (id integer primary key, name text, weight real) strict;
INSERT INTO "foo" VALUES(1,'Lila',2.31);
COMMIT;
```
This is mainly useful as a debugging feature, and it doesn't look like I can achieve the equivalent using the `.backup()` method.

I'm probably going to use the same workaround as @evansd here, using `sqlite3.dump._iterdump()`.

**Comment by coleifer** [comment]
Why should one do that using a gross hack and a Python library when it is already provided out-of-the-box by the Sqlite shell?

```sh
$ echo ".dump" | sqlite3 /tmp/strict-table.db
```

**Comment by simonw** [comment]
Because I can't guarantee that the user will have the SQLite shell installed - especially once I start using `pysqlite3` to bundle SQLite 3.37.0 (with support for strict tables), since the user's `sqlite3` shell is likely to be for a previous version.

**Comment by coleifer** [comment]
That shouldn't affect the dump functionality, if I understand the changelog correctly:

https://www.sqlite.org/stricttables.html#accessing_strict_tables_in_earlier_versions_of_sqlite

**Comment by simonw** [comment]
Yes that's true - surprisingly this works with my older `sqlite3` client:

```
% sqlite3 :memory: 'select sqlite_version()'
3.28.0
% sqlite3 /tmp/strict-table.db .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE foo (id integer primary key, name text, weight real) strict;
INSERT INTO foo VALUES(1,'Lila',2.3100000000000000532);
COMMIT;
```

**Comment by simonw** [comment]
I've implemented the `sqlite3.dump._iterdump` workaround now in https://github.com/simonw/sqlite-utils/commit/c91f1e6957fc7f3678a04f23d969e587ed4eacb9 so I no longer have a vested interest in whether or not `pysqlite3` brings back `iterdump()`, but I thought you'd find my use-case for it relevant to this issue.
