### ISSUE TITLE
enable sqlite math functions

### ISSUE THREAD

**Issue by fgregg** [coleifer/pysqlite3#33]
thanks so much for this valuable package!

it would be great if the built-in math functions were enabled by adding the -DSQLITE_ENABLE_MATH_FUNCTIONS as a compilation flag

(https://www.sqlite.org/compile.html#enable_math_functions)

**Comment by coleifer** [comment]
There should be new wheels on pypi (0.4.7) that include this.

**Comment by fgregg** [comment]
thank you so much!
