### ISSUE TITLE
SQL compilation caching

### ISSUE THREAD

**Issue by AbdealiJK** [coleifer/pysqlite3#35]
I get this error when I try to use pysqlite3

> Dialect sqlite:pysqlite will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Dialect maintainers should seek to set this attribute to True after appropriate development and testing for SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)

**Comment by coleifer** [comment]
Looks like it should support it, I'd take it up with sqlalchemy maintainers.

https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/dialects/sqlite/pysqlite.py#L445-L447
