### ISSUE TITLE
Please update pysqlite3-binary to 3.38.2 and track latest automatically.

### ISSUE THREAD

**Issue by arcivanov** [coleifer/pysqlite3#36]
Thank you for the project! 
Could you please update the binary to the latest 3.38.2? There are data correctness fixes.
Thanks!

**Comment by coleifer** [comment]
Yes, you're right. 0.4.7.post3 is up on pypi now and I've removed the problematic 0.4.7.

**Comment by adipon** [comment]
What changed between build 0.4.7 and 0.4.7.post3?
Why was 0.4.7 release deleted?

**Comment by coleifer** [comment]
There was an issue in sqlite itself 3.38, which could lead to incorrect query results.

**Comment by rittneje** [comment]
@coleifer In the future, please do not delete releases from PyPI. That breaks builds.

**Comment by evansd** [comment]
@coleifer I think the correct thing here would have been to "[yank](https://pypi.org/help/#yanked)" the release. That would mark it as problematic and prevent people from using it accidentally while not breaking builds which pin to this version.
