### ISSUE TITLE
pysqlite3-binary still using old SQLite version

### ISSUE THREAD

**Issue by isratmir** [coleifer/pysqlite3#39]
Hi. Want to use SQLite v3.38.

Installed library and expected there'll be the new version of SQLite. But 
 
`pipenv install pysqlite3-binary`

"version": "==0.4.7.post5"

![image](https://user-images.githubusercontent.com/1897701/174982111-37fe4a62-64a8-4b89-ba25-a36536aaeaa7.png)

Am I missing something?

**Comment by AbdealiJK** [comment]
I came across this cause I thought I had a similar issue.
Digging a bit more I realized I had mixed up which environment I has `pysqlite3` and which environment I had `pysqlite3-binary`
Once I opened the python shell in the correct environment - it worked fine :+1:
