### ISSUE TITLE
Build wheels for macOS and Windows

### ISSUE THREAD

**Issue by edgarrmondragon** [coleifer/pysqlite3#42]
The [`cibuildwheel`](https://github.com/pypa/cibuildwheel) project seems like a good option for this   and seems easy enough to add to this repo.

What do you think?

If there's interest, I can start work on a PR 🙂

**Comment by coleifer** [comment]
Going to pass for now, thanks.

**Comment by mihow** [comment]
@edgarrmondragon would you be interested in starting a new fork? My colleagues really need a Windows version of this package so we can use the latest SQLite features on their systems. `cibuildwheel` seems like a great project.

**Comment by edgarrmondragon** [comment]
@mihow yeah, something like a `pysqlite3-wheels` package that just pulls this repo and builds all the right wheels should be good enough for a lot of folks. I might be able to give it a try on the weekend.

**Comment by Dobatymo** [comment]
Please have a look at my fork which builds wheels for all platforms using `cibuildwheel`.
https://github.com/Dobatymo/pysqlite3
https://pypi.org/project/pysqlite3-wheels/

**Comment by mihow** [comment]
Awesome, thanks @Dobatymo I will test your fork.
