### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by mihow** [coleifer/pysqlite3#44]
This is a great project, thank you! But unfortunately we can't use it any software because not all of our colleagues are on Linux.

**Comment by coleifer** [comment]
Surely it will compile on windows if you have sqlite3 header and shared library.

**Comment by mihow** [comment]
Is there documentation on that? Currently it is not possible to `pip install pysqlite3` or `pysqlite3-binary`

**Comment by coleifer** [comment]
>Currently it is not possible to pip install pysqlite3

How is that?

**Comment by Sums123** [comment]
Hi guys, I'm also having issues building on Windows
Visual Studio Build Tools 2022 is installed
![image](https://user-images.githubusercontent.com/29928499/211015593-0261244d-2574-4479-8c1d-359a7ee38e89.png)

I added the sqlite library according to this thread. 
https://github.com/dlang-community/d2sqlite3/issues/49
It also fails, when I change "Machine" to x86

When compiling I get the following issue:
LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x86\\link.exe' failed with exit code 1181

Full error message
![image](https://user-images.githubusercontent.com/29928499/211016927-022b1332-4c19-42c2-8a51-28641754d041.png)

When trying to run install through pip, I get the same error
![image](https://user-images.githubusercontent.com/29928499/211017084-048c5e48-31b6-47d3-a4f9-12d1c9d42e9c.png)

**Comment by r0ny123** [comment]
Hi @coleifer, I am too having issues when building pysqlite3 on windows (Visual Studio Build Tools 2022) as @Sums123 stated above.

**Comment by coleifer** [comment]
You appear to be missing sqlite3 headers.

**Comment by r0ny123** [comment]
But I can successfully build it using pysqlite3==0.4.8

**Comment by r0ny123** [comment]
Hey, @coleifer pinging again, can you take a look?
