### ISSUE TITLE
please update repo with sqlite code from Python 3.7 (backup API)

### ISSUE THREAD

**Issue by FelixSchwarz** [coleifer/pysqlite3#5]
I'd like to use sqlite's backup API which was exposed in Python 3.7. As written in the README this repo is based on Python 3.6. Is it possible to upgrade the repo?

**Comment by coleifer** [comment]
The backup API is already present.

**Comment by FelixSchwarz** [comment]
Thank you for the quick response and sorry for wasting your time. I just assumed the API is not present as Python 3.6 does not provide it.
