### ISSUE TITLE
No binary wheels for pysqlite3-binary for python_version 3.10 and manylinux1

### ISSUE THREAD

**Issue by visuman** [coleifer/pysqlite3#59]
Is it possible to support wheels for python_version 3.10 and manylinux1 ?

until 0.4.6 an python version =3.9 the package supported this 
https://pypi.org/project/pysqlite3-binary/0.4.6/#files

related to https://github.com/coleifer/pysqlite3/issues/50

**Comment by coleifer** [comment]
See also #40 

I suggest for now just modifying the script in the `build_scripts/` directory and publishing your own wheels. Everything is handled for you in the scripts so it should be very easy for you to create your own if you need them.
