### ISSUE TITLE
Installing pysqlite3-binary through pip gets: "Could not find a version that satisfies the requirement pysqlite3-binary (from versions: none)"

### ISSUE THREAD

**Issue by trancethehuman** [coleifer/pysqlite3#64]
<img width="902" alt="Screenshot 2023-09-17 at 11 52 09 PM" src="https://github.com/coleifer/pysqlite3/assets/16231195/d48de997-7dca-49f0-a861-aa4f0a6e6d19">

**Comment by coleifer** [comment]
I don't publish wheels for your os/architecture.

**Comment by nalgeon** [comment]
@trancethehuman you can try [sqlean.py](https://github.com/nalgeon/sqlean.py), which is a drop-in replacement for `pysqlite3` with binaries for Windows, Linux and macOS.

**Comment by trancethehuman** [comment]
@nalgeon thank you
