### ISSUE TITLE
Building wheels for Windows?

### ISSUE THREAD

**Issue by andreped** [coleifer/pysqlite3#69]
I have been using this package as part of a Docker build. But for local development on Windows, we are having issues, as we do not have access to C++ build tools. Hence, it would be of value to have precompiled binaries for Windows as well.

I see that you have precompiled binaries for Python 3.6-3.12 for manylinux [here](https://pypi.org/project/pysqlite3-binary/#files), but could you add the same for Windows.

You likely do not have this, as you are running the builds locally on a Linux desktop. But I would suggest just making a GitHub Actions workflow for this.

If you want, I can draft up a PR for this, which produces the binaries for Windows and Linux.

cc: @coleifer

---
EDIT: It would even be possible to use `twine` to push built binaries to PyPI directly, if of interest. But thats up to you what you want. Alternatively, just storing the precompiled binaries are Artifacts is a simple way to solve this, but then you would need to manually download these and run these `twine` command locally.

**Comment by coleifer** [comment]
I haven’t used windows in 15 years, I suggest setting up your own build process to generate the wheels.

**Comment by andreped** [comment]
> I haven’t used windows in 15 years, I suggest setting up your own build process to generate the wheels.

Well, you would be surprised how many people that use Windows.

What if I draft a CI that builds these wheels for you, across both Linux and Windows?

I would think this is of interest to a large portion of devs.

**Comment by coleifer** [comment]
No interest here, but other interested parties are welcome to set up a build process for wheels.

**Comment by nalgeon** [comment]
@andreped maybe try [sqlean.py](https://github.com/nalgeon/sqlean.py), which is based on `pysqlite3` and provides builds for Windows, Linux and macOS.

**Comment by andreped** [comment]
> @andreped maybe try [sqlean.py](https://github.com/nalgeon/sqlean.py), which is based on `pysqlite3` and provides builds for Windows, Linux and macOS.

@nalgeon That looks like exactly what I want! Thank you for the great suggestion, @nalgeon! :]
