### ISSUE TITLE
Adding encryption support

### ISSUE THREAD

**Issue by kitzune4real** [coleifer/pysqlite3#70]
Hello,
I am wondering if you are interested implementing [this](https://utelle.github.io/SQLite3MultipleCiphers/) as a feature.
I tried to add the `sqlite3_key_v2()` function to the `connection.c` file + editing the `PyArg_ParseTupleAndKeywords` plus the variables for a password as a simple string but I am running into a `segfault`. I also tried to change `sqlite3_open_v2()` to `sqlite3_open()` because I was unsure the `schema` argument for `sqlite3_key_v2()` but it ended with them same `segfault`. Since I am not that experienced with python module programming, maybe I missed something that is required. `SQLite3MultipleCiphers` works on a simple test c file for me without this segfault.

Maybe you have the time, the will and the same opinion that this would be a nice feature to implement.

Thanks in advance.

EDIT: By the way the build went well and the segfault is:
```
Program received signal SIGSEGV, Segmentation fault.
sqlite3mcCodecSetup (passwordLength=8, userPassword=0x7ffff3312360 "password", cipherType=0, codec=0xb5f3d8)
    at ../src/cipher_common.c:249
249       codec->m_hmacCheck = sqlite3mcGetCipherParameter(globalParams, "hmac_check");
```

**Comment by coleifer** [comment]
No plans for adding this, but for those interested you can use the [sqlcipher3](https://github.com/coleifer/sqlcipher3) project -- this project provides the same driver code as pysqlite3 (this repo) but instead links against libsqlcipher3. The keys can easily be managed via `pragma` statements and an additional API is not needed.

**Comment by coleifer** [comment]
Eh, why not here they are: 513803c230a2821a2369910944a7aa0750fa3d8a
