### ISSUE TITLE
No ARM builds available.

### ISSUE THREAD

**Issue by illeatmyhat** [coleifer/pysqlite3#72]
There are no ARM builds available. [This is not difficult to do with github workflows (they have windows, mac, linux runners on x86 and ARM)](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
See an example here: https://github.com/IBM/kstar/blob/main/.github/workflows/main.yaml#L8-L31

In a `redhat/ubi9-minimal` docker image, I'm attempting to install pysqlite3-binary, but get the error
```
ERROR: Could not find a version that satisfies the requirement pysqlite3-binary (from versions: none)
ERROR: No matching distribution found for pysqlite3-binary
```

minimum reproducable example:

`docker buildx build --platform=linux/amd64,linux/arm64 -f ./Dockerfile .`
```dockerfile
# syntax=docker/dockerfile:1
FROM redhat/ubi9-minimal as builder

RUN microdnf update -y && \
    microdnf install -y python3.11-devel python3.11-pip && \
    pip3.11 install --no-cache-dir -U pip && \
    pip3.11 install pysqlite3-binary
```

**Comment by illeatmyhat** [comment]
FYI for anyone who just wants to get it built, do this instead.
```dockerfile
# syntax=docker/dockerfile:1
FROM redhat/ubi9-minimal as builder

RUN microdnf update -y && \
    microdnf install -y gcc sqlite-devel python3.11-devel python3.11-pip && \
    pip3.11 install --no-cache-dir -U pip && \
    pip3.11 install pysqlite3
```

**Comment by coleifer** [comment]
Yeah, the prebuilt binaries are x86-64. ARM or other architectures can build from source.
