### ISSUE TITLE
pip install failing with no matching distribution found error

### ISSUE THREAD

**Issue by BPrasad123** [coleifer/pysqlite3#76]
Hi,

I am using python:3.10.14-bullseye image and "pip install mysqlite3-binary" throws the following error.

ERROR: Could not find a version that satisfies the requirement pysqlite3-binary (from versions: none)
ERROR: No matching distribution found for pysqlite3-binary

However, the same setup was working fine a few days back. I am not sure what changed recently. Could you please guide how to solve this issue?

Thanks

**Comment by coleifer** [comment]
Not sure try installing the sqlite3 and python headers and just compiling pysqlite3.
