### ISSUE TITLE
No module name 'pysqlite3._sqlite3' on CentOS Linux 7 (Core)

### ISSUE THREAD

**Issue by princi-pol** [coleifer/pysqlite3#8]
I have compiled a specific version of SQLite with the CLFAG -DSQLITE_ENABLE_LOAD_EXTENSION and then I have dowloaded the sources of pysqlite3 and followed the steps in the guide. I also have done ```python setup.py install``` but when I try to do 

```
python3 -c "import pysqlite3"
```
I get the errors:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/paolotr/pySqlite/pysqlite3-0.4.1/pysqlite3/__init__.py", line 23, in <module>
    from pysqlite3.dbapi2 import *
  File "/home/paolotr/pySqlite/pysqlite3-0.4.1/pysqlite3/dbapi2.py", line 28, in <module>
    from pysqlite3._sqlite3 import *
ModuleNotFoundError: No module named 'pysqlite3._sqlite3'
```
Before doing this, I have uninstalled the pysqlite3-binary (which is installed by default on the docker imageI am using) by doing pip3 uninstall pysqlite3-binary.

If useful, the gcc compiler is 6.3.1

Thanks a lot for any suggestion.

**Comment by coleifer** [comment]
It looks like your project is pointing to the sources for pysqlite3, but not the actual build directory where the C extension is put. So if you clone the source code you will see `pysqlite3/` and `src/` directories, but when you go to build the extension it puts everything (including C extension) in `build/lib.python.../pysqlite3/`.

I'd suggest either check-out the code to a different directory so it isn't getting picked up on your PYTHONPATH, or doing `python setup.py build_ext -i` to drop the c extension into the `pysqlite3/` directory.

**Comment by rbrecheisen** [comment]
Hi sorry to get back to the question above but I can't make it work unfortunately. As soon as I type python setup.py install I get these SSL errors which is weird because if I do a regular pip install -r requierements.txt inside my project it runs without such errors. Something else seems to be triggering them. Do you have other ideas that might cause this? Thanks!

**Comment by coleifer** [comment]
You can see from the setup.py that we don't depend on ssl in any way. I have no idea but it doesn't seem to me that your issue is related to pysqlite3.

**Comment by rbrecheisen** [comment]
Ok thanks for the quick feedback. I'll keep on searching :)
